MAde a good bit of progress this morning. Cleaned up Inline big time and got it ready for its big job- being the main data structure throughout the program runtime.
the ability to pass parents and packages into the inline
constructor is working. However, we are still hitting the bug:
"attributeError: 'list' object has no attribute 'split'"
I get why inheritance or multiple class inlines would
cause this error, but not a generic inline spec like
"classA : attr1, attr2 : method1 : -e"